module.exports = {
  content: ['./app/**/*.php', './resources/**/*.{php,vue,js}'],
  safelist: [
    'rounded',
    'max-w-xs',
    'sm:max-w-none',
    'sm:justify-start',
    'sm:justify-end',
    'sm:justify-center',
    'md:max-w-none',
    'md:justify-start',
    'md:justify-end',
    'md:justify-center',
    'lg:items-start',
    'xl:items-start',
    'lg:text-left',
    'mr-3',
    'p-4',
    'py-0.5',
    'pl-2.5',
    'pr-1',
    'ml-0.5',
    'h-4',
    'w-4',
    'gap-y-6',
    'drop-shadow-md',
    '-mx-3',
    'sm:grid',
    'sm:col-span-5',
    'sm:col-span-7',
    'sm:grid-cols-12',
    'lg:grid-cols-1',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'lg:grid-cols-5',
    'lg:grid-cols-6',
    'lg:grid-cols-7',
    'lg:grid-cols-8',
    'lg:grid-cols-9',
    'lg:grid-cols-10',
    'lg:grid-cols-11',
    'lg:grid-cols-12',
    'xl:grid-cols-1',
    'xl:grid-cols-2',
    'xl:grid-cols-3',
    'xl:grid-cols-4',
    'lg:col-span-1',
    'lg:col-span-2',
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-5',
    'lg:col-span-6',
    'lg:col-span-7',
    'lg:col-span-8',
    'lg:col-span-9',
    'lg:col-span-10',
    'lg:col-span-11',
    'lg:col-span-12',
    'lg:col-auto',
    'sm:gap-10',
    'sm:gap-6',
    'sm:gap-x-8',
    'sm:gap-x-10',
    'sm:gap-x-12',
    'sm:gap-x-16',
    'sm:gap-x-24',
    'sm:gap-x-32',
    'lg:gap-10',
    'lg:gap-x-6',
    'lg:gap-x-8',
    'lg:gap-x-10',
    'lg:gap-x-12',
    'lg:gap-x-16',
    'lg:gap-x-24',
    'lg:gap-x-32',
    'sm:grid-cols-2',
    'sm:grid-cols-3',
    'sm:grid-cols-4',
    'max-w-xs',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-5xl',
    'max-w-6xl',
    'max-w-7xl',
    'text-white',
    'text-dark',
    'text-light',
    'text-morado',
    'text-violet',
    'text-light-gradient',
    'sm:flex-row',
    'sm:ml-2',
    'hover:bg-action-dark',
    'hover:text-white',
    'group-hover:bg-action',
    'group-hover:bg-violet',
    'sm:hidden',
    'bg-dark',
    'bg-violet',
    'bg-orchid',
    'sm:basis-1/5',
    'sm:basis-1/6',
    'sm:basis-1/4',
    'sm:basis-2/6',
    'sm:basis-2/4',
    'sm:basis-full',
    'sm:basis-1/12',
    'sm:basis-2/12',
    'sm:basis-3/12',
    'sm:basis-4/12',
    'sm:basis-5/12',
    'sm:basis-6/12',
    'sm:basis-7/12',
    'sm:basis-8/12',
    'sm:basis-9/12',
    'sm:basis-10/12',
    'sm:basis-11/12',
    'md:basis-1/5',
    'md:basis-1/6',
    'md:basis-1/4',
    'md:basis-2/6',
    'md:basis-2/4',
    'md:basis-full',
    'lg:basis-1/5',
    'lg:basis-1/6',
    'lg:basis-1/4',
    'lg:basis-2/6',
    'lg:basis-2/4',
    'lg:basis-full',
    'basis-auto',
    'sm:basis-auto',
    'md:basis-auto',
    'basis-1/5',
    'basis-1/4',
    'basis-2/6',
    'basis-2/4',
    'basis-full',
    'border-light',
    '-mb-14',
    'border-8',
    'border-action-lighter-blue',
    'py-9',
    'sm:flex-1',
    'min-h-[475px]',
    'sm:min-h-[600px]',
    'w-5/6',
    'sm:w-4/6',
    'text-action-dark',
    'opacity-25',
    '-left-28',
    'lg:ml-0',
    'xl:ml-0',
    'xl:left-0',
    '2xl:left-0',
    '3xl:left-0',
    'bg-indigo-50',
    'bg-green-50',
    'bg-yellow-50',
    'bg-red-50',
    'sm:w-auto'
  ],
  theme: {
    fontFamily: {
      'sans': ['Proxima Nova', 'ui-sans-serif', 'system-ui'],
      'display': ['Proxima Nova'],
      'body': ['Proxima Nova'],
      'space': ['Space Mono', 'monospace'],
      'syne': ['Syne', 'sans-serif'],
    },
    colors: {
      inherit: 'inherit',
      current: 'currentColor',
      transparent: 'transparent',
      white: '#ffffff',
      black: '#000000',
      primary: 'orange',
      secondary: '#2874af',
      brand: '#2c405a',
      action: '#2874af',
      'dark-blue' : '#182a44',
      'action-dark': '#105890',
      'action-light-blue': '#52b4ff',
      'action-lighter-blue' : '#3B8BCA',
      dark: '#182a44',
      redish: '#FF4F4F',
      'redish-dark': '#DA3D3D',
      light: '#eef5fc',
      'light-gradient': '#eef5fc',
      'light-gray': '#F9FAFB',
      purple: '#825EB8',
      morado: '#712F79',
      violet: '#9D53FC',
      orchid: '#AA67FF',
      verde: '#117E15',
      'rojo' : '#CF2A2A',
      orange : '#DA6625',
      'marketing' : {
        2: '#2F71F4', // blue
        9: '#F270A3', // pink
        11: '#F07012', // orange
        14: '#619E66', // green
      },
      'red': {
        50: '#FEF2F2',
        400: '#F87171',
        600: '#DC2626',
      },
      'yellow': {
        50: '#FEFCE8',
        400: '#FACC15',
      },
      'green': {
        50: '#F0FDF4',
        400: '#4ADE80',
      },
      'indigo': {
        50: '#EEF2FF',
        500: '#6366F1',
        600: '#4F46E5',
        700: '#4338CA',
      },
      'blue': {
        100: '#eef5fc', // pale blue
        200: '#e3ebf3', // medium pale blue
        300: '#c7d8e8', // dark pale blue
        400: '#52b4ff', // action light blue
        600: '#2c405a',
        900: '#182a44', // dark blue
      },
      'gray': {
        50: '#F9FAFB',
        100: '#F3F4F6',
        200: '#E5E7EB',
        300: '#D1D5DB',
        400: '#828282',
        500: '#9ca3af',
        700: '#374151',
        800: '#1F2937',
      }
    },
    extend: {
      borderRadius: {
        'lg' : '10px',
      },
      lineHeight: {
        'leading-5': '1.5',
        'leading-6': '1.5',
        'leading-tight': '1.5',
      }
    },
  },
  plugins: [],
};
